development:
  adapter: postgresql
  encoding: unicode
  database: myapp_dev
  pool: 5
  username: dietertimmermann
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: dietertimmermann
  password:
